AE:
  BruteForce:
    # Failed login attempts threshold (account locking)
    failedAttemptsThreshold: 5

    # Notification mail on account locking
    notificationMail: # Available variables "domain", "accountIdentifier", "ip", "failedAttemptsThreshold"
      from:
        email: 'noreply@{domain}'
        name: 'Brute-force prevention ({domain})'
      to:
        email: '' # Optional
        name: '' # Optional
      subject: 'Account disabled due to failed login attempts ({domain})'
      message: |
        The account "{accountIdentifier}" has been deactivated at {time} due to too many
        failed login attempts ({failedAttemptsThreshold})

        Last attempt from {ip}